#!/usr/bin/env bash
# This script configures the SSH client to use the private key ~/.ssh/school and refuse to authenticate using a password

echo "
Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
" >> ~/.ssh/config

